name: The Hitchhiker's Guide to Compression
title: The Hitchhiker's Guide to Compression
description: A collection of resources and posts to help people understand compression algorithms.
footer-links:
  github: go-compression/go-compression.github.io
# url: https://go-compression.github.io/

url: "" # blank in development
permalink: pretty

# development: true # optional, you can use in liquid tag conditionals

exclude: [node_modules, gulpfile.js]

plugins:
  - jekyll-spaceship

sass:
  sass_dir: _sass

source: site

readme_index:
  enabled: false

# remote_theme: pmarsceill/just-the-docs
theme: "just-the-docs"

footer_content: 'If you see something off, please consider <a href="https://go-compression.github.io/contributing/">contributing</a>.'

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "https://github.com/go-compression/go-compression.github.io"

# last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
# last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/go-compression/go-compression.github.io" # the github URL for your repo
gh_edit_source: site
gh_edit_branch: "master" # the branch that your docs is served from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately
